# -*- coding: utf-8 -*-
"""NLP_prac_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KmGHvNXtCUn7LKeegoh_JGCLOHYDx_qd
"""

import re
s =  "I AM NARAYAN"
res = re.search(r"\bA",s)
print(res.re)
print(res.string)

import re
string = "Welcome to amity"
pattern = "[a-m]"
result = re.findall(pattern,string)
print(result)

import re
s1 = input('Enter a pattern to check :')
m = re.match(s1 , 'Python is a language')
print('start index is : ' , m.start()) ,
print('end index is :' , m.end())
print('Matched string is :' , m.group())

import re
s = input("Enter pattern to check:")
m = re.fullmatch(s,"python srinivas")
if m != None:
  print("Match is available at the beginning of")
  print('start index is :',m.start()),
  print('end index is:',m.end())
  print('Match string is:',m.group())
else:
  print("Match is not available at the beginnign of the string")





import re
target_string = 'python is easy to learning'
sub_string = input ("enter any sub string:")
match_object = re.search(sub_string,target_string)
if match_object:
  print('yes,we have a match.')
  print('the match start in ',match_object.start())
  print("the match end in ",match_object.group())
else:
  print('NO,WE DONT HAVE NAY MACTH.')

import re
target_string = 'python is easy to learning'
m = re.search("^python.*learning$",target_string)
if m:
  print('yes,we have a match ')
else:
  print('No,we dont have any match')

import re
target_string = 'python is easy to learning'
m = re.search("\s",target_string)
if m:
  print('yes, we ahve a match')
  print('the first white-space charecter is located in position:',m.start())
else:
  print('no,we dont have any match')

import re
pattern_str = input("Enter pattern to check:")
result = re.findall(pattern_str,"python is a languge.python is easy.")
if len(result) != 0:
  print(pattern_str,"match is available in Target String")
  print(result)
else:
  print(pattern_str,"match is not available in Target string")

import re
digits_lists = re.findall("[0-9]","9py9th4on8 Sr8ina5vas3rao025")
print(digits_lists)

import re
values_list = re.findall('[\D]' , "1py23th5on la96ngu3age2")
string_data = ''.join(values_list)
print(string_data)

import re
values_list = re.findall('[a-zA-Z\s]',"1py23th5on la96ngu3age2")
string_data = ''.join(values_list)
print(string_data)

import re
end_digits = re.findall("25$","9py9th4on8 sr8ini5va3srao025")
print(end_digits)

import re
list_data = re.findall(r"\w*","Fly in the sky.")
print(list_data)
for word in list_data:
  data = re.search(r"[aeiou]",word)
  if word!=''and data==None:
    print(word)

import re
string ='Error should never pass silently.Unless explicitly silenced.'
obj = re.findall(r'\b[aeiouAEIOQU]\w+',string)
print(obj)

import re
m = re.split('\s',"python is a language.python is easy.")
print(m)

import re
m = re.split('\s',"python is a language. python is easy.",2)
print(m)

import re
result = re.sub('[a-zA-Z]',"#","9sdvvsd8sdf6sx4xsdf33")
print(result)

import re
result = re.subn('[a-zA-Z]',"#","9py9th4on8 sr8ini5va3srao025")
print(result)
print("The Result String:",result[0])
print("The Result String of replcaement:",result[1])

from re import finditer
string = "Try to earn while you learn"
iter_object = finditer("earn",string)
for match in iter_object:
  print(match.span())
  print('start index is :',match.start()),
  print('end index is :',match.end())
  print('matched string is :',match.group())
  print()

from re import *
pattern = compile(r'[aeiou]')

string = "flat is better than nested. Sparse is better than dense.xyz"
list_of_words = split('\s',string)
for word in list_of_words:
  print(word,'---->>',pattern.match(word))

for word in list_of_words:
  print(word,'---->>',pattern.search(word))

import re
string = 'Simple is better than complex. Complex is better than complicated.'
pattern = re.compile(r'is')
obj1 = pattern.match(string)
obj2 = pattern.search(string)
obj3 = pattern.findall(string)
obj4 = pattern.sub(r'was',string)

if obj1:
  print("input string biggens with 'is' word",)
else:
  print("input string not biggens with 'is 'word",)

if obj2:
  print("input string contain 'is'word at",obj2.start(),"position")

else:
  print("input string not conatin 'is'word")

if obj3:
  print("Result is:",obj3)
else:
  print("input string not conatin 'is',word")

if obj4:
  print(obj4)
else :
  print("input string not contain 'is'word")