# -*- coding: utf-8 -*-
"""NLP_lab_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-Frf4CaTZRU--w4Rwxu9Epp2l0HAIGx
"""

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

text = [
    "I love this product",
    "This is terrible",
    "I am so happy today",
    "I hate this movie",
    "What a wonderful world",
    "This is the worst thing ever",
    "I really enjoy this",
    "I am very sad"
]

#labels(1=positive, 0 = negative)
labels = [1,0,1,0,1,0,1,0]

X_train,X_test,y_train,y_test = train_test_split(texts,labels,test_size=0.24,random_state=0)

#convert text to numeric from(bag of words)

vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)
#Train a Naive Bayes model
model = MultinomalNB()
model.fit(X_train,y_train)

#test model accuracy
y_pred = model.predict(X_test_vec)
print("Accuracy:",accuracy_score(y_test,y_pred))

#Test with new text
new_text = ["I really enjoy this"]
new_vec = vectorixer.transform(new_text)
prediction = model.predict(new_vec)

if prediction[0] == 1:
  print("Positive Text")
else:
    print("Negative Text")

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

texts = [
    "I love this product",
    "This is terrible",
    "I am so happy today",
    "I hate this movie",
    "What a wonderful day",
    "This is the worst thing ever",
    "I really enjoy this",
    "I am very sad"
]

# Labels (1 = Positive, 0 = Negative)
labels = [1, 0, 1, 0, 1, 0, 1, 0]

X_train, X_test, y_train, y_test = train_test_split(texts, labels, test_size=0.25, random_state=0)

# Convert text to numeric form (bag of words)
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Train a Naive Bayes model
model = MultinomialNB()
model.fit(X_train_vec, y_train)

# Test model accuracy
y_pred = model.predict(X_test_vec)
print("Accuracy:", accuracy_score(y_test, y_pred))

# Test with new text
new_text = ["I really enjoy this"]
new_vec = vectorizer.transform(new_text)
prediction = model.predict(new_vec)

if prediction[0] == 1:
    print("😊 Positive Text")
else:
    print("😠 Negative Text")