# -*- coding: utf-8 -*-
"""NLP_lab3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xiHogjDeOFGStlgSbTBq6NmFlgiB2XTl
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Sample dataset
data = {
    'tweet': [
        "I hate you",
        "You are so stupid",
        "Have a wonderful day",
        "You are amazing",
        "I despise your behavior",
        "What a lovely person you are",
        "I can't stand you",
        "You make me smile"
    ],
    'label': [1, 1, 0, 0, 1, 0, 1, 0]   # 1 = Hate speech, 0 = Not hate speech
}

# Create DataFrame
df = pd.DataFrame(data)

# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(
    df['tweet'], df['label'], test_size=0.25, random_state=0
)

# Convert text into numerical features
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Train a Naive Bayes model
model = MultinomialNB()
model.fit(X_train_vec, y_train)

# Make predictions
y_pred = model.predict(X_test_vec)

# Evaluate accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Test with a new tweet
new_tweet = ["I hate your attitude"]
new_tweet_vec = vectorizer.transform(new_tweet)
prediction = model.predict(new_tweet_vec)

if prediction[0] == 1:
    print("⚠ Hate Speech Detected")
else:
    print("✅ Not Hate Speech")